[book]
language = "en"
src = "src"
title = "Wipple Guide"

[output.html]
site-url = "/docs/"
no-section-label = true
smart-punctuation = true
additional-js = ["js/custom.js"]

[output.html.code.hidelines]
wipple = "#"
